### ISSUE TITLE
допы списком

### ISSUE THREAD

**Issue by AlekseiKlimkin** [bobahml/marsala#1]
хорошо бы допы добавить списком

**Comment by bobahml** [comment]
Захардкодим на стороне сервера - такой список:

Также дополнительно мы вам предлагаем:  
Добавки к блюдам  
50г.   Огурцы соленые                         30р.
50г.   Сыр                          30р.
50г.   Сметана                          30р.
50г.   Майонез                          30р.
50г.   Горчица                          30р.
50г.   Аджика                            30р.
50г.   Кисло-сладкий соус                          30р.
50г.   Соевый соус                           30р.
50г.   Соус Чили                           30р.
